### ISSUE TITLE
Test library resistance against Preimage Attack

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/merkle-patricia-tree#39]
There is a new (?) attack vector against merkle tree implementations described in this post:
https://flawed.net.nz/2018/02/21/attacking-merkle-trees-with-a-second-preimage-attack/

Currently it is unclear if this affects this library. This should be tested.

**Comment by medvedev1088** [comment]
Just my thoughts here.

The attack on the Merkle tree is possible because preimages of intermediate nodes can be used as leaf nodes in a new tree, resulting in different trees having the same root. This can be easily fixed by running a different preprocessing function for leaf and intermediate nodes before hashing them (this way using a preimage of an intermediate node as a leaf will result in a different hash). For example, prepend a different byte to leaf and intermediate nodes before hashing them (this solution is also given in the referenced article).

The Modified Merkle Patricia tries used in Ethereum naturally have this fix:
- Any leaf or extension node is a 2-item node, so are differentiated from branch nodes, which are 17-item nodes (to be specific, any RLP-encoded branch node can never be confused with any RLP-encoded leaf or extension node). 
- Further, leaf nodes are prepended with `0010` or `0011` nibble so they can be differentiated from extension nodes, that are prepended with `0000` and `0000`. 

As the result, there is no way to use preimages of branch and extension nodes as leaf nodes, which makes the attack impossible.

**Comment by holgerd77** [comment]
Thanks for the explanation. I will leave this open for some time for reference and other to recap.
