### ISSUE TITLE
Library fails branch-value-update test

### ISSUE THREAD

**Issue by no2chem** [ethereumjs/merkle-patricia-tree#54]
Upstream in the official tests, a new test "branch-value-update" was added:

```json
  "branch-value-update": {
    "in": [
      [ "abc", "123" ],
      [ "abcd", "abcd" ],
      [ "abc", "abc" ]
    ],
    "root": "0x7a320748f780ad9ad5b0837302075ce0eeba6c26e3d8562c67ccc0f1b273298a"
  }
```

This library fails that test. In particular, it seems that search stops at an extension node when it should check the value in the branch node.

**Comment by holgerd77** [comment]
Hi Michael @no2chem, just discovered your library fork, pretty interesting, have to have a closer look when time permits. Thanks for contributing back to the original library on discovering bugs! 😄

**Comment by holgerd77** [comment]
Hi @no2chem, hi @SoujanyaPonnapalli, just had a (somewhat) closer look at your fork repository, great work, congrats! I wonder if we can take back some of your changes to this library, so that users of this version also can benefit. Recalled the first commits you were doing, at least for the first 4-5 commits I didn't discover anything which wouldn't be applicable and useful for the original library.

Are you open for an exchange if we find some common path here?

**Comment by no2chem** [comment]
Hi @holgerd77 ! Thanks! I do think there's some things that could be ported back to this library (admittedly, a lot of that library is research and we're very liberal with changing APIs), but you're right that a lot of it might not be applicable to this library. Probably the most obvious one is to use ES6 stuff, and maybe decoupling from the leveldb api. We're of course open to an exchange.

As we add new features though, we'll probably encounter some things worth porting (notably, some of those things are issues that people have opened in this repo).

**Comment by holgerd77** [comment]
Sounds great, we can also definitely point to your library from this one for people with different use cases, would you recommend that people can use this in production use cases or has this still somewhat experimental nature?

Also then you probably don't mind if we from time to time go through your PRs and then cherry-pick stuff from there, eventually adopt it a bit and then do a PR with this here, since we are low on people being able to directly maintain the library atm and I think this would really help. And you are of course also continue to be very invited to do parallel PRs. 😄 

Actually we ARE very open to ES6 changes and updates to make the library more readable, also eventually to TS stuff, then we just need to add the respective transpilation steps.

**Comment by holgerd77** [comment]
//cc @alextsg at the moment, we should probably focus more on VM stuff, but if you want you are very invited to keep an eye on this and eventually take over some of the changes over time
